### ISSUE TITLE
Unable to get magisk installed upon fresh install of AOSP

### ISSUE THREAD

**Issue by lmaoggrofl** [sfX-android/android_vendor_extendrom#47]
# Description

Hi I am trying to build magisk into my aosp by following this guide (https://github.com/sfX-android/android_vendor_extendrom/wiki/Setup)
But when i do the following command and flash, magisk doesnt appear in my android.
I tried rebooting the device (Pixel5a) a couple of time but still no new app icon for magisk.

source build/[envsetup.sh](https://envsetup.sh/)
m j-15
fastboot flashall -w

# Required(!) information

- custom OS name you build for (e.g. LOS, AXP.OS, ...) -> AOSP
- Android version (e.g. A9, A10, A11, ...) -> A12
- COMPLETE(!!!) output when executing: `vendor/extendrom/er.sh` -> (see "Note" topic) [er.sh output](https://gist.github.com/lmaoggrofl/23aa5e62777ff0d9a98fa56ee7544909)
- content of `vendor/extendrom/Android.mk` after running extendrom/a build  -> (see "Note" topic) [Android.mk](https://gist.github.com/lmaoggrofl/20e17b8cea0ef4d79275304a055637c2)

**Comment by steadfasterX** [comment]
> Adding on to the previous post.
> 
> Upon flashing AOSP and rebooting the phone, i do not see the magisk apk appearing on my phone. I also tried to install the apk manually and the phone is still not rooted
> 
> I cant find any logs starting with `Starting: <YOUR-PATH-HERE>/vendor/extendrom/config/magisk/patch.sh with: [.....]` but this is my [full build output](https://gist.github.com/lmaoggrofl/f1e2f75e3749c30d772fad5a530df1ca)

yes that is the reason for your issues then. it seems the patching was  successful while it simply does not execute it.
note: you are the first one trying to use extendrom with AOSP so we might need to adjust things for that kind of OS first.

if you open the file `build/make/tools/releasetools/common.patch` and search for `EXTENDROM` you should find the adjustment made. it can also be just the build target you are using. it seems you use

`m -j 15`

what happens when you adjust this to 

`m -j 15 otapackage | tee -a buildota.log`

and share the `buildota.log` afterwards.

also what instructions and exact OS do you build here? any wiki pages, github sources etc?


> Faced some build issue with er.mk [offending entries](https://gist.github.com/lmaoggrofl/6db5dacdf0032a2979e12b3c130d40fa)

especially for this the OS info is required and the device tree you are using (device/google/barbet or sim) would be helpful.

**Comment by steadfasterX** [comment]
closed due to no feedback
